version: "3.1"

services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf_iot
    networks:
      new_bridge:
        ipv4_address: 172.20.0.4
    volumes:
      - ./containers/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - '8094:8094'
      - '8092:8092'
      - '8125:8125'  
    
  influxdb:
    image: influxdb:1.8
    container_name: influxdb_iot
    restart: always
    networks:
      new_bridge:
        ipv4_address: 172.20.0.2
    volumes:
      - ./containers/influxdb_task_storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_USER=den
      - INFLUXDB_USER_PASSWORD=1
    ports:
      - '8086:8086'

      
  grafana:
    image: grafana/grafana:latest
    networks:
      new_bridge:
        ipv4_address: 172.20.0.5
    container_name: grafana_iot
    ports:
      - '8888:8888'

  mosquitto:
    image: eclipse-mosquitto:1.6.14
    networks:
      new_bridge:
        ipv4_address: 172.20.0.3
    container_name: mosquitto_iot
    ports:
      - '1883:1883'
      - '9001:9001'
  
  python_publisher:
    image: justsafin/python_publisher:1.0
    networks:
      new_bridge:
        ipv4_address: 172.20.0.5
    container_name: python_iot
    
networks:
  new_bridge:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
