version: "3.1"

services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf_iot
    networks:
      - bridge
    volumes:
      - ./containers/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    
  influxdb:
    image: influxdb:1.8
    container_name: influxdb_iot
    restart: always
    networks:
      - bridge
    volumes:
      - ./containers/influxdb_task_storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_USER=den
      - INFLUXDB_USER_PASSWORD=1 
      
  grafana:
    image: grafana/grafana:latest
    networks:
      - bridge
    container_name: grafana_iot

  mosquitto:
    image: eclipse-mosquitto:1.6.14
    networks:
      - bridge
    container_name: mosquitto_iot
    
  python_publisher:
    image: justsafin/python_publisher:1.0
    networks:
      - bridge
    container_name: python_iot
    
networks:
  bridge:
    driver: bridge
    ipam:
     config:
       - subnet: 172.17.0.0/16
         gateway: 172.17.0.1
         aux_addresses:
           telegraf: 172.17.0.5
           influxdb: 172.17.0.3      
           grafana: 172.17.0.4
           mosquitto: 172.17.0.2
           python_publisher: 172.17.0.6
